### PR TITLE
Build clean up

### PR DESCRIPTION
**Pull request by jdillon**
Some additional changes to allow the testsuite to run better, and a bunch of general clean up to the build configuration... lots more to do, but its overwhelming so little by little.

### CODE REVIEW

**Comment by wjprakash** [comment]
Merging and building now ...

**Comment by wjprakash** [comment]
Do I need to run the test with some flag.. It takes for ever. I simple ran the hudson-test-harness with mvn install
Here is my result so far

Running CoreJellyTest
Tests run: 495, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.613 sec
Running hudson.bugs.DateConversionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.942 sec
Running hudson.bugs.JnlpAccessWithSecuredHudsonTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.14 sec
Running hudson.bugs.LoginRedirectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.345 sec
Running hudson.bugs.seasar.Operation2174Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.186 sec
Running hudson.ClassicPluginStrategyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.456 sec
Running hudson.cli.BuildCommandTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.991 sec <<< FAILURE!
Running hudson.cli.EnableJobCommandTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.366 sec <<< FAILURE!
Running hudson.console.ConsoleAnnotatorTest
Tests run: 7, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 78.746 sec <<< FAILURE!
Running hudson.console.ExceptionAnnotationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.851 sec
Running hudson.console.UrlAnnotatorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.078 sec
Running hudson.diagnosis.HudsonHomeDiskUsageMonitorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.772 sec
Running hudson.diagnosis.TooManyJobsButNoViewTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.432 sec
Running hudson.ExceptionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.562 sec
Running hudson.ExtensionListTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 49.644 sec <<< FAILURE!
Running hudson.GroovyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.696 sec
Running hudson.logging.LogRecorderManagerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.082 sec
Running hudson.markup.MarkupFormatterTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 26.661 sec <<< FAILURE!
Running hudson.matrix.MatrixProjectDependencyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.334 sec
Running hudson.matrix.MatrixProjectTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 157.267 sec
Running hudson.matrix.MatrixTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.662 sec
Running hudson.maven.Maven3BuildTest
Tests run: 8, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 107.319 sec <<< FAILURE!
Running hudson.maven.MavenBuildSurefireFailedTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 63.028 sec <<< FAILURE!
Running hudson.maven.MavenBuildTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 148.467 sec
Running hudson.maven.MavenEmptyModuleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.794 sec
Running hudson.maven.MavenJellyTest
Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.073 sec
Running hudson.maven.MavenMultiModuleTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 216.375 sec
Running hudson.maven.MavenOptsTest

**Comment by jdillon** [comment]
It takes about 45 minutes for me, with those failures.  I've yet to work on fixing them or speeding it up... right now I'm settling for always finishing to build w/o crashing Maven.

**Comment by wjprakash** [comment]
Do you build and run with some flag, because it seems to take more than 45 min for me. I'm on Mac 10.6.  I'll let the test complete and let you know the time it takes. Earlier one I killed in between.

**Comment by jdillon** [comment]
If run from the top-level, then:

mvn -Dit -Pdebug clean install

or from hudson-test-harness:

mvn clean install

I think the only significant changes for the harness in these commits are forkMode=always and using -ea for tests.  Most others are unrelated to the harness specifically.

**Comment by wjprakash** [comment]
Here is the result

Tests run: 834, Failures: 24, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:49:52.840s
[INFO] Finished at: Fri Feb 25 14:56:40 PST 2011
[INFO] Final Memory: 33M/81M

**Comment by wjprakash** [comment]
Merged

**Comment by jdillon** [comment]
yikes, well ~2hrs certainly isn't what I saw.  If you still have it can you paste me the times each test took?

**Comment by wjprakash** [comment]
Fortunately I didn't close the terminal.

Running CoreJellyTest
Tests run: 495, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.686 sec
Running hudson.bugs.DateConversionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.188 sec
Running hudson.bugs.JnlpAccessWithSecuredHudsonTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.013 sec
Running hudson.bugs.LoginRedirectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.74 sec
Running hudson.bugs.seasar.Operation2174Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.798 sec
Running hudson.ClassicPluginStrategyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.517 sec
Running hudson.cli.BuildCommandTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.127 sec
Running hudson.cli.EnableJobCommandTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.74 sec <<< FAILURE!
Running hudson.console.ConsoleAnnotatorTest
Tests run: 7, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 84.826 sec <<< FAILURE!
Running hudson.console.ExceptionAnnotationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.245 sec
Running hudson.console.UrlAnnotatorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.672 sec
Running hudson.diagnosis.HudsonHomeDiskUsageMonitorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.765 sec
Running hudson.diagnosis.TooManyJobsButNoViewTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.311 sec
Running hudson.ExceptionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.009 sec
Running hudson.ExtensionListTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 58.766 sec <<< FAILURE!
Running hudson.GroovyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.78 sec
Running hudson.logging.LogRecorderManagerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.28 sec
Running hudson.markup.MarkupFormatterTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 29.124 sec <<< FAILURE!
Running hudson.matrix.MatrixProjectDependencyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.758 sec
Running hudson.matrix.MatrixProjectTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 176.341 sec
Running hudson.matrix.MatrixTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.667 sec
Running hudson.maven.Maven3BuildTest
Tests run: 8, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 119.431 sec <<< FAILURE!
Running hudson.maven.MavenBuildSurefireFailedTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 66.029 sec <<< FAILURE!
Running hudson.maven.MavenBuildTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 149.547 sec
Running hudson.maven.MavenEmptyModuleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.81 sec
Running hudson.maven.MavenJellyTest
Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.091 sec
Running hudson.maven.MavenMultiModuleTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 234.431 sec
Running hudson.maven.MavenOptsTest
Process 1298669393106 is killed.
Running hudson.maven.MavenProjectTest
Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 190.353 sec <<< FAILURE!
Running hudson.maven.MavenSnapshotTriggerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 121.041 sec
Running hudson.maven.RedeployPublisherTest
Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 148.035 sec <<< FAILURE!
Running hudson.maven.reporters.MavenSiteArchiverTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.155 sec
Running hudson.maven.reporters.SurefireArchiverTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.533 sec
Running hudson.model.AbstractBuildTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.571 sec
Running hudson.model.AbstractProjectTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 140.346 sec
Running hudson.model.ApiTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.373 sec
Running hudson.model.ComputerSetTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.63 sec
Running hudson.model.DependencyGraphTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.226 sec
Running hudson.model.DirectoryBrowserSupportTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.023 sec
Running hudson.model.DownloadServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.602 sec
Running hudson.model.ExecutorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.02 sec
Running hudson.model.ExternalRunTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.976 sec
Running hudson.model.FreeStyleProjectTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 98.874 sec
Running hudson.model.HelpLinkTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 90.559 sec
Running hudson.model.HudsonTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 123.167 sec
Running hudson.model.JobPropertyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.066 sec
Running hudson.model.JobTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 84.043 sec
Running hudson.model.labels.LabelAtomPropertyTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.996 sec <<< FAILURE!
Running hudson.model.labels.LabelExpressionTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 106.158 sec
Running hudson.model.listeners.ItemListenerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.084 sec
Running hudson.model.ManagementLinkTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.181 sec
Running hudson.model.ParametersTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 65.208 sec
Running hudson.model.queue.LoadPredictorTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.173 sec <<< FAILURE!
Running hudson.model.queue.WideExecutionTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.536 sec <<< FAILURE!
Running hudson.model.QueueTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.339 sec
Running hudson.model.SlaveTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.149 sec
Running hudson.model.UpdateCenter2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.608 sec
Running hudson.model.UsageStatisticsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.204 sec
Running hudson.model.UserTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.146 sec
Running hudson.model.ViewTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 65.024 sec
Running hudson.node_monitors.DiskSpaceMonitorDescriptorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.673 sec
Running hudson.pages.SystemConfigurationTestCase
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.359 sec <<< FAILURE!
Running hudson.PluginManagerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.95 sec
Running hudson.scm.ScmTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.294 sec
Running hudson.search.SearchTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.54 sec
Running hudson.security.CliAuthenticationTest
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 27.227 sec <<< FAILURE!
Running hudson.security.csrf.DefaultCrumbIssuerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 90.384 sec
Running hudson.security.ExtendedReadPermissionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 60.242 sec
Running hudson.security.HudsonPrivateSecurityRealmTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.672 sec
Running hudson.security.LDAPSecurityRealmTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.647 sec
Running hudson.security.LoginTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.484 sec
Running hudson.security.PermissionGroupTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.896 sec
Running hudson.slaves.ComputerConnectorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.736 sec
Running hudson.slaves.EnvironmentVariableNodePropertyTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 103.792 sec
Running hudson.slaves.JNLPLauncherTest
Process 1298672134228 is killed.
Running hudson.slaves.NodeCanTakeTaskTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 41.23 sec <<< FAILURE!
Running hudson.slaves.NodeProvisionerTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 86.364 sec <<< FAILURE!
Running hudson.tasks._ant.AntTargetAnnotationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.583 sec
Running hudson.tasks.AntTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 68.193 sec
Running hudson.tasks.ArtifactArchiverTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 59.827 sec
Running hudson.tasks.BuildTriggerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 124.509 sec
Running hudson.tasks.EnvVarsInConfigTasksTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 71.514 sec <<< FAILURE!
Running hudson.tasks.junit.CaseResultTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 86.106 sec
Running hudson.tasks.junit.HistoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.703 sec
Running hudson.tasks.junit.JUnitParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.408 sec
Running hudson.tasks.junit.JUnitResultArchiverTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 112.868 sec
Running hudson.tasks.junit.TestResultLinksTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.823 sec
Running hudson.tasks.junit.TestResultPublishingTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 143.246 sec
Running hudson.tasks.LogRotatorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 68.653 sec
Running hudson.tasks.MailAddressResolverTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.611 sec
Running hudson.tasks.MailerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 107.386 sec
Running hudson.tasks.MavenTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 89.254 sec
Running hudson.tasks.ShellTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.082 sec
Running hudson.tasks.test.TestResultExtensionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.598 sec
Running hudson.tools.JDKInstallerTest
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 300.009 sec <<< FAILURE!
Process 1298673696295 is killed.
Running hudson.tools.ToolLocationNodePropertyTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 66.757 sec <<< FAILURE!
Running hudson.tools.ToolLocationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.072 sec
Running hudson.triggers.SCMTriggerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.76 sec
Running hudson.UDPBroadcastThreadTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.966 sec
Running hudson.util.ArgumentListBuilder2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.097 sec
Running hudson.util.FormFieldValidatorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.967 sec
Running hudson.util.ProcessTreeKillerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.87 sec
Running hudson.util.XStreamTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.538 sec
Running hudson.views.ListViewColumnTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.571 sec
Running lib.form.AdvancedButtonTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.332 sec
Running lib.form.DropdownListTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.274 sec
Running lib.form.EnumSetTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.096 sec
Running lib.form.ExpandableTextboxTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.01 sec
Running lib.form.NameRefTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.255 sec
Running lib.form.PasswordTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.314 sec
Running lib.form.RepeatableTest
Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 128.811 sec <<< FAILURE!
Running lib.form.ValidateButtonTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.074 sec
Running lib.hudson.ListScmBrowsersTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 61.691 sec
Running org.jvnet.hudson.main.AppTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 23.761 sec

Results :

Failed tests: 

Tests in error: 

Tests run: 834, Failures: 24, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:49:52.840s
[INFO] Finished at: Fri Feb 25 14:56:40 PST 2011
[INFO] Final Memory: 33M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project hudson-test-harness: There are test failures.
[ERROR]

**Comment by jdillon** [comment]
dizam.  Well, some of this I can fix, others... maybe not (yet/easily).  hudson.tools.JDKInstallerTest ran for me, this appears to actually try and fetch a real JDK installer, so if your network was slow then it could skew the results.  I'll look at this more over the weekend.

**Pull request merged**
