### PR TITLE
Update to latest sisu-inject container (works around embedded maven issues)

### PR DESCRIPTION
**Pull request by mcculls**

### CODE REVIEW

**Comment by mcculls** [comment]
In case you're wondering why the "locator.add(injector);" line was removed this is because it's redundant. The shared locator has a setter method marked with @Inject that accepts the injector being constructed. This means any injector that includes a binding to the shared locator will automatically add itself when the injector is constructed. (This is necessary because the application might access the locator during the bootstrap process.)

**Comment by jdillon** [comment]
I was about to suggest this, having looked over our internal smoothie stuff its already updated to use sisu-inject-bean 2.1.1.

**Comment by tonit** [comment]
Hey Stuart, thanks for providing this.
I tried https://github.com/tonit/hudson/commits/injection-bugfix but without success for the M3 project yet.

Get well soon!

**Comment by mcculls** [comment]
Hi Toni - which version of M3 are you using?  I used Maven 3.0.2 and that worked for some local projects.
You could try clearing out "~/.hudson/plugins/maven-plugin*" to force Hudson to refresh the plugin cache...

**Comment by tonit** [comment]
maven 3.0.2. i also worked with an entirely fresh hudson work folder (using mvn hpi:run on a pretty fresh hudson plugin skeleton project). I will try again later/tomorrow.

**Comment by jdillon** [comment]
Maven 3.0.2 uses sisu-inject-bean 1.4.3.1, and is not compatible with 2.1.1.  Maven 3.0.3-SNAPSHOT uses 2.1.1 (and should be released soonish IIRC).

**Comment by tonit** [comment]
oh.. okay. So would suggest https://grid.sonatype.org/ci/view/Maven/job/maven-3.0.x-bootstrap/1321/jdk=java-5x,label=ubuntu/ ?

**Comment by mcculls** [comment]
Maven 3.0.2 works for me:

> Started by user anonymous
> Found mavenVersion 3.0.2 from file jar:file:/Users/mcculls/Tools/maven-3/lib/maven-core-3.0.2.jar!/META-INF/maven/org.apache.maven/maven-core/pom.properties
> Parsing POMs
> [bundleplugin] $ java -Xmx512m -XX:MaxPermSize=128m -cp /Users/mcculls/.hudson/plugins/maven-plugin/WEB-INF/lib/maven3-agent-1.397-SNAPSHOT.jar:/Users/mcculls/Tools/maven-3/boot/plexus-classworlds-2.4.jar org.jvnet.hudson.maven3.agent.Maven3Main /Users/mcculls/Tools/maven-3 /Users/mcculls/Tools/tomcat/webapps/hudson/WEB-INF/lib/hudson-remoting-1.397-SNAPSHOT.jar /Users/mcculls/.hudson/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-1.397-SNAPSHOT.jar 53925
> <===[HUDSON REMOTING CAPACITY]===>channel started
> Executing Maven:  -B -f /Users/mcculls/Code/felix/bundleplugin/pom.xml clean install -V
> Apache Maven 3.0.2 (r1056850; 2011-01-09 00:58:10+0000)
> Java version: 1.6.0_22, vendor: Apple Inc.
> Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
> Default locale: en_US, platform encoding: MacRoman
> OS name: "mac os x", version: "10.6.6", arch: "x86_64", family: "mac"
> [INFO] Scanning for projects...

What error are you seeing Toni?

**Comment by tonit** [comment]
okay.. getting into it:
- running sole war (java -jar hudson.war) works, - did not try that before
- mvn hpi:run with correct hudson version does not work (old problem from gist)

So right now i suspect a leaking maven plugin executor from "hpi:run".

**Comment by jdillon** [comment]
Yes, the hpi plugin could be using the wrong set of dependencies.  That wouldn't surprise me at all... :-\

**Comment by wjprakash** [comment]
Getting the hpi sources and pushing to the core, then we can debug the issue

**Comment by wjprakash** [comment]
This is causing merge conflict at SmoothieComponent. Could you pull the master merge and resubmit for pull

**Comment by mcculls** [comment]
Resubmitting...

**Pull request closed without merging**
