### PR TITLE
Updates for hudson-test-harness

### PR DESCRIPTION
**Pull request by jdillon**
A bunch of fixes for hudson-test-harness to work better with smoothie.  Some tests are still failing, need to investigate more.  Tests will run slower for now.  The smoothie stuff was never designed to be used as the hudson-test-harness' TestPluginManager wants them.  So I'm forcing everything to use the LocalPluginManager for now.  Will look at improving the performance later, though IIRC this was always slow, so I'm not sure how much slower use of the LocalPluginManager is making things.

Added hudson-test-harness into a profile so you can:

mvn -Dit -Pdebug

The -Pdebug is required to build, its an active by default profile (which should be removed) which won't activate if another profile is activated.

### CODE REVIEW

**Comment by wjprakash** [comment]
Merged

**Comment by wjprakash** [comment]
Jason you might want to look at why they are slow. I switched to sure-fire few weeks ago from so called home grown junit-maven-plugin. Most of the tests took an average of 2-5 seconds. Now I'm seeing several order of magnitude higher i.e from 10 to 100 of sec on Mac.

**Comment by jdillon** [comment]
Its not use of surefire, its assumptions the harness was making about how plugins would be used/loaded.  Once I can sort out the remaining failures I'll look at how to optimize.

**Comment by jdillon** [comment]
These tests make some assumptions, which probably aren't very good... I'm consistently seeing:

Running hudson.model.HelpLinkTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 3.038 sec <<< FAILURE!
Running hudson.model.HudsonTest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

With forkMode=always, it gets past this.  So something in the tests are really messing with the execution of Maven.

**Pull request merged**
