### PR TITLE
Outgoing/findbugs

### PR DESCRIPTION
**Pull request by henriklynggaard**
Fix for 5 findbugs warnings
- RemoteInvocationHandler.java:177, NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENT,
- InstallPluginCommand.java:119, NP_NULL_ON_SOME_PATH
- Maven3Main.java:99, NP_NULL_ON_SOME_PATH
- ProxyConfiguration.java:147, RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION
- Descriptor.java:783, DLS_DEAD_LOCAL_STORE,

### CODE REVIEW

**Comment by wjprakash** [comment]
Henrik, 

I'm on vacation and can't look in to any of these until Next Monday. I'm hopping some one will attend to your pull request before Monday
- Winston

**Comment by mcculls** [comment]
Reviewed, tested, and merged - thanks!

**Comment by wjprakash** [comment]
Hi Henrik,

Thanks for your patch and your willingness to support Hudson. 

I don't want to give any excuse for what happened in the past. But I'm committed to make Hudson a successful Open Source Project, contrary to many claim Oracle has vested personal interest in the project, which IMO is not true.

As I studied the latest unique pings from various installation of Hudson, almost 13-15k active users are using Hudson 1.396 & 1.398. So a large user base is still using Hudson.

However, I want to encourage the plugin developers also and make them to develop Plugins for Hudson also along with Jenkins.

May I ask your suggestion on how to win back the confidence of plugin developers. Hope I'm not putting you on the spot :)

Thanks,

Winston

Sent from my iPhone

**Comment by henriklynggaard** [comment]
Hi Winston

I think that question can be answered from several angles, but in essence it comes down to two basic things, "Value" as why should or shouldn't I support Hudson, and "Price" how easy is it to support Hudson or how many hoops I need to jump through in order to add Hudson support.

### Value

When reading below please keep in mind that I am talking about perceptions not facts :-)

In my opinion nobody walked away from the fork looking good, but some people perceive things differently with Oracle being the bad guy. I don't think there is a easy cure for such bad blood except a consistently good track record  going forward. 

As it is now Hudson still appears to be more "closed" than Jenkins and you can get the feeling  many of the things are being discussed behind closed doors. I see several things you can do to  get rid of that appearance.
- Encourage that all discussions between Oracle and Sonatype happens in the developer mailing list. 
- If a customer provides feedback to Oracle outside the Hudson community channels, try an make a "how do we solve XXX" post on the user or developer mailing list. 
- Jenkins has a bi-weekly governance meeting where they normally discuss big ticket items.Hudson should have something similar. I don't know if it is relevant to call it a governance meeting (see next item) or if is should just be called sprint meeting.
- When writing this I tried to find a page describing the governance model for Hudson but I could not locate any. I think you need to at least  document the current model.Also if it doesn't already exist consider setting up a governance board (I have some more thoughts on this but leaving them out for now)
- Hudson also appears to be slowing down development wise, some of which can be explained by the switch to to month long release cycle. With such a (relatively speaking) long  release cycle (and very short track record), it is important that things don't start to appear stale. My suggestion would be to post some kind of road map of the big ticket items, e.g. when sonatype is integrating the new maven integration. Also start to mark issues in jira with target fix version when a issue has been planned for release.
- In Jenkins I also have easy access to see unreleased changes. I don't need any JIRA skills, I can go to the normal change log and just click "Upcoming changes". Hudson should replicate that
- Another place where Hudson appears to be slowing down, is when you compare changelogs. I know Hudson has spent a lot of time stabilizing and cleaning up, but it doesn't take up much space in the changlog. _It is however also the reason why my CI server can build Hudson reliably while Jenkins fails randomly :-)_ One suggestion so that Hudson does not suffer from the "Jenkins got the fix, Hudson doesn't" issue, would be to have one person looking over the shoulder of Jenkins and porting their core fixes to Hudson.
- Get a hudson_release twitter account like jenkins_release.

The above may seem like a rant of various issues with Hudson that I like to see fixed, but I my mind these are some of the things Hudson could do so that it comes of as a living evolving project that I as Joe random plug-in developer would want to contribute to and more to the point invest time in supporting.

### Price

I wouldn't say the price is high as in it is difficult to support Hudson, but on the other hand I did end up with a 4 post documentary on how to do it ;-) There are some easy wins, most of which deals with making it easier when the plug-ins are hosted elsewhere.
- The update centre json must pick up new versions automatically.
- Work with Jenkins on establishing a shared repository for plug-ins, maybe by getting them to post directly to maven central or by having their repository sync with maven central.
- Alternatively have the update centre fetch plug-ins from jenkins maven repo as well as maven central.
- Make sure the project-information on the Hudson wiki is correct. see http://blog.hlyh.dk/2011/04/supporting-both-hudson-jenkins-part-5.html for the relevant issue reports
- Lessen the need for Hudson wiki pages by having a automatically generated catalogue meaning a web version of the in-app Hudson update centre. Maybe work with jenkins on how to better categorise plug-ins.
- Make sure the wiki and hudson-ci site is very developer friendly. For instance where is the javadoc ? http://hudson-ci.org/javadoc/ points to 1.386 :-. My suggestion would be to start creating a new "developer centre" part of the wiki by cleaning up the "Extend Hudson" page.
- Look into @fcamblor's plug-ins tester (https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Compatibility+Tester).
- promote http://hudson-ci.org/hudson/ which currently only builds the core.. make it easy to get a job added to build you plug-in. (to start with it could be a mail to the developer mailing list). extend the list of administrators so you don't become a bottleneck

I think this covers it for now, but there may be more ideas later. Should we move this discussion to the developer mailing list ? it might be easier to find and contribute to there rather than attached to a "random" Github pull request

Best regards
Henrik

**Comment by wjprakash** [comment]
Henrik,

Thanks for the detailed explanation on what could be improved. We can move this discussion to dev list. I will try to address the issues you mentioned.

I want to make one point very clear. If you or any one having the impression, Oracle and Sonatype is discussing behind the scene, then I want to assure you that is incorrect. What ever we planned to do is already discussed in the mailing. We are not planning anything behind the scene with out the community's knowledge. 

The community already know what are the planned big ticketed items (long term plan).

As for as from Oracle side I have plans to fix the issues and enhancements from the Jira only, apart from planning for the long term goals.

Let us continue this discussion on Monday.

Thanks,

Winston

**Comment by wjprakash** [comment]
Henrik,

I thought this an excellent list of suggestions, so I let know my
management  to take necessary actions to implement the suggestions.
Ted, my VP has tasked Susan Duncan to work with you to implement these
suggestions. She will contact you soon.

Feel free to send the  list to the dev mailing list to get the
community suggestions also.
- Winston

On Saturday, April 30, 2011, henriklynggaard
reply@reply.github.com
wrote:

> Hi Winston
> 
> I think that question can be answered from several angles, but in essence it comes down to two basic things, "Value" as why should or shouldn't I support Hudson, and "Price" how easy is it to support Hudson or how many hoops I need to jump through in order to add Hudson support.
> 
> ### Value
> 
> When reading below please keep in mind that I am talking about perceptions not facts :-)
> 
> In my opinion nobody walked away from the fork looking good, but some people perceive things differently with Oracle being the bad guy. I don't think there is a easy cure for such bad blood except a consistently good track record  going forward.
> 
> As it is now Hudson still appears to be more "closed" than Jenkins and you can get the feeling  many of the things are being discussed behind closed doors. I see several things you can do to  get rid of that appearance.
> - Encourage that all discussions between Oracle and Sonatype happens in the developer mailing list.
> - If a customer provides feedback to Oracle outside the Hudson community channels, try an make a "how do we solve XXX" post on the user or developer mailing list.
> - Jenkins has a bi-weekly governance meeting where they normally discuss big ticket items.Hudson should have something similar. I don't know if it is relevant to call it a governance meeting (see next item) or if is should just be called sprint meeting.
> - When writing this I tried to find a page describing the governance model for Hudson but I could not locate any. I think you need to at least  document the current model.Also if it doesn't already exist consider setting up a governance board (I have some more thoughts on this but leaving them out for now)
> - Hudson also appears to be slowing down development wise, some of which can be explained by the switch to to month long release cycle. With such a (relatively speaking) long  release cycle (and very short track record), it is important that things don't start to appear stale. My suggestion would be to post some kind of road map of the big ticket items, e.g. when sonatype is integrating the new maven integration. Also start to mark issues in jira with target fix version when a issue has been planned for release.
> - In Jenkins I also have easy access to see unreleased changes. I don't need any JIRA skills, I can go to the normal change log and just click "Upcoming changes". Hudson should replicate that
> - Another place where Hudson appears to be slowing down, is when you compare changelogs. I know Hudson has spent a lot of time stabilizing and cleaning up, but it doesn't take up much space in the changlog. _It is however also the reason why my CI server can build Hudson reliably while Jenkins fails randomly :-)_ One suggestion so that Hudson does not suffer from the "Jenkins got the fix, Hudson doesn't" issue, would be to have one person looking over the shoulder of Jenkins and porting their core fixes to Hudson.
> - Get a hudson_release twitter account like jenkins_release.
> 
> The above may seem like a rant of various issues with Hudson that I like to see fixed, but I my mind these are some of the things Hudson could do so that it comes of as a living evolving project that I as Joe random plug-in developer would want to contribute to and more to the point invest time in supporting.
> 
> ### Price
> 
> I wouldn't say the price is high as in it is difficult to support Hudson, but on the other hand I did end up with a 4 post documentary on how to do it ;-) There are some easy wins, most of which deals with making it easier when the plug-ins are hosted elsewhere.
> - The update centre json must pick up new versions automatically.
> - Work with Jenkins on establishing a shared repository for plug-ins, maybe by getting them to post directly to maven central or by having their repository sync with maven central.
> - Alternatively have the update centre fetch plug-ins from jenkins maven repo as well as maven central.
> - Make sure the project-information on the Hudson wiki is correct. see http://blog.hlyh.dk/2011/04/supporting-both-hudson-jenkins-part-5.html for the relevant issue reports
> - Lessen the need for Hudson wiki pages by having a automatically generated catalogue meaning a web version of the in-app Hudson update centre. Maybe work with jenkins on how to better categorise plug-ins.
> - Make sure the wiki and hudson-ci site is very developer friendly. For instance where is the javadoc ? http://hudson-ci.org/javadoc/ points to 1.386 :-. My suggestion would be to start creating a new "developer centre" part of the wiki by cleaning up the "Extend Hudson" page.
> - Look into @fcamblor's plug-ins tester (https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Compatibility+Tester).
> - promote http://hudson-ci.org/hudson/ which currently only builds the core.. make it easy to get a job added to build you plug-in. (to start with it could be a mail to the developer mailing list). extend the list of administrators so you don't become a bottleneck
> 
> I think this covers it for now, but there may be more ideas later. Should we move this discussion to the developer mailing list ? it might be easier to find and contribute to there rather than attached to a "random" Github pull request
> 
> Best regards
> Henrik
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hudson/hudson/pull/31#issuecomment-1081170

## 
- Winston

**Comment by henriklynggaard** [comment]
Winston, 

First days back to work after 14 days vacation was a bit hectic, but I have now posted the discussion on the developer mailing list. I posted a slightly edited version where I incorporated some of your comments.

I am looking forward to hearing from Susan and seeing what we can come up with.

Best regards
Henrik

**Comment by wjprakash** [comment]
Welcome back. Hope you had a wonderful vacation. Thanks for posting your 
comments to the community.
- Winston
  > Winston,
  >
  > First days back to work after 14 days vacation was a bit hectic, but I have now posted the discussion on the developer mailing list. I posted a slightly edited version where I incorporated some of your comments.
  >
  > I am looking forward to hearing from Susan and seeing what we can come up with.
  >
  > Best regards
  > Henrik
  >

**Pull request merged**
