### PR TITLE
Fixed 'Hudson-Version: null' in hpi manifest after the packing 

### PR DESCRIPTION
**Pull request by antkozak**
Fixed 'Hudson-Version: null' in hpi manifest after the packing

### CODE REVIEW

**Comment by mcculls** [comment]
FYI, I've opened a separate pull request https://github.com/hudson/hudson/pull/34 with what I believe to be the correct fix. Note that using MavenProject.getDependencies() is not really advised because the version string won't be normalised and may still include ranges, etc. It also may not match the actual (resolved) version used to build and test against.

**Comment by mcculls** [comment]
To see the issue with using MavenProject.getDependencies() you can test it with the following dependency:

```
    <dependency>
        <groupId>org.jvnet.hudson.main</groupId>
        <artifactId>hudson-core</artifactId>
        <version>[2.0.0]</version>
        <scope>provided</scope>
    </dependency>
```

While Maven resolves this version range to 2.0.0 in getArtifacts() the unresolved range still appears in getDependencies()

**Comment by mcculls** [comment]
Can you try the fix in https://github.com/hudson/hudson/pull/34 - if you agree with it then this request can be closed.

**Comment by antkozak** [comment]
I've verified your fix, it works well and covers more test cases, so I'm closing this request. There is one more issue, I'll add comment in https://github.com/hudson/hudson/pull/34.

**Pull request closed without merging**
