### PR TITLE
HUDSON-8932

### PR DESCRIPTION
**Pull request by mosabua**
Fixed signup links to work in non toplevel contexts as well.

Fixed exception from parsing uri.

This probably needs some testing and enhancements.

### CODE REVIEW

**Comment by mcculls** [comment]
I'm going to try a slightly different fix that shouldn't involve changing those static links, will keep you posted.

**Comment by mcculls** [comment]
Hi Manfred, could you see if https://github.com/hudson/hudson/pull/116 also fixes the issue you saw? It works for me locally using Tomcat (and doesn't require any changes to the signup links) but a second opinion would be good.

**Comment by mcculls** [comment]
Ignore that... I finally found the bad signup URL (the one on the top-right is OK, the one in the main body is not)

**Comment by mcculls** [comment]
Merged, I'll run some additional tests against that URI parsing code and try to make it more robust

**Comment by 8nevil8** [comment]
No, I mean that we should revert only changes for loginDialog*properties.

**Comment by mcculls** [comment]
On 21 Jul 2011, at 15:26, 8nevil8 wrote:

> No, I mean that we should revert only changes for loginDialog*properties.

Righto, I see what you mean

**Comment by mosabua** [comment]
Imho absolute links will always be wrong. And I think Stuart found a fix for it that I am testing now..

**Pull request merged**
