### PR TITLE
Improved language 

### PR DESCRIPTION
**Pull request by mosabua**
changed from

Last Successful Artifacts to Artifact(s) of Last Successful Build

and changed to plural for test results

### CODE REVIEW

**Comment by mosabua** [comment]
Done without the year so that we don't need to change it later..

**Comment by mosabua** [comment]
imho this is ready to merge..

**Comment by mosabua** [comment]
Somehow github automatically added my latest commit that enforces maven 3 plus... oh well. Might as well pull that in too. Once you have done that I will update the wiki. Or I can do the merge myself if you are ok with it.

**Comment by wjprakash** [comment]
You have write access to hudson. If no comments for a while, you can merge it yourself

**Comment by mosabua** [comment]
Ok. Is that generally the case going forward? Just so I know when I can merge myself. I dont want to overstep you..

**Comment by wjprakash** [comment]
Basically, if it is a  feature or bug fix that would affect functionality and need to get QA involved, then a issues need to be created and the fix  is discussed and the code is reviewed. However, if it is a minor fix like the above, it is OK to self merge if no comments for more than few hours.

**Comment by mosabua** [comment]
Cool.. I will follow that. We should put something like that as contributor guidelines on the wiki..

**Pull request merged**
