### PR TITLE
HUDSON-8829: make sure provided scope dependencies are included when determining the Hudson-Version header

### PR DESCRIPTION
**Pull request by mcculls**
http://issues.hudson-ci.org/browse/HUDSON-8829

### CODE REVIEW

**Comment by mcculls** [comment]
This is a non-trivial change so it should be reviewed by another core developer before it gets merged.

**Comment by antkozak** [comment]
I've verified the fix, it works well. I found one more issue: I think hpi creates incorrect "Plugin-Dependencies" section in matifest if plugin contains dependency in test scope or plugin has transitive dependency on another plugin.
Example: 
git plugin manifest after the building contains: 
Plugin-Dependencies: parameterized-trigger:2.4;resolution:=optional,subversion:2.0.1-SNAPSHOT,maven-plugin:2.0.1
cvs plugin:
Plugin-Dependencies: maven-plugin:2.0.1,subversion:1.11
It's possible to resolve it with maven exclusions, but it's not convenient.
To resolve it I propose to extend method in AbstractHpiMojo:

```
private String findDependencyProjects() throws IOException, MojoExecutionException {
    StringBuilder buf = new StringBuilder();
    for (Artifact artifact : getResolvedDependencies()) {
        if (HpiUtil.isPlugin(artifact) &&  !Artifact.SCOPE_TEST.equals(artifact.getScope()) &&
                artifact.getDependencyTrail().size() <= 2) {
            if (buf.length() > 0){
            ......
```

Thanks

**Comment by mcculls** [comment]
Are you talking about the actual plugin header in the HPI/JAR or the test HPL file (target/test-classes/the.hpl) which does include test dependencies? It's not clear whether the test HPL should include all test dependencies or not - the old code was inconsistent in this regard because it included non-plugin test dependencies, but excluded plugin test dependencies.

The new getResolvedDependencies() method excludes test dependencies by default, unless "includeTestScope" is set to true. This is the same as the old code in AbstractHpiMojo, the only difference is that the TestHplMojo now explicitly sets "includeTestScope" to true - this is to match the old behaviour where non-plugin test dependencies were included in the Libraries header in "target/test-classes/the.hpl". But because we use getResolvedDependencies() everywhere this also means that plugin test dependencies are included under the Plugin-Dependencies header in "target/test-classes/the.hpl". 

As far as I can tell this shouldn't cause any problems, in fact it should make things more consistent because we're now using a single approach to discover resolved dependencies (both plugin and non-plugin). But if "target/test-classes/the.hpl" should not contain plugin test dependencies then any fix needs to go into TestHplMojo and not AbstractHpiMojo because there are other subclasses of AbstractHpiMojo that do expect to include test plugin dependencies (see the RunMojo).

IMHO unless there's a specific problem caused by this change I propose that we stick with treating both plugin and non-plugin scopes the same, as at least it's consistent.

Wrt. transitive plugin dependencies, we are matching the old plugin behaviour - looking at the plugin strategy code this should not cause any problems because of the way the classloader delegation works. In fact removing transitive plugin dependencies could adversely affect the plugin strategy (both classic and new) because it doesn't do any traversal of dependencies, ie. some of the core code expects the plugin dependency list to include transitive entries.

**Comment by antkozak** [comment]
Hello,
I see your point. I'm worried about strange dependency description in git plugin. It has dependency on parameterized-trigger 2.4 which contains dependency on: subversion 1.4. As result git plugin after the building has such dependency line in git.hpi:
Plugin-Dependencies: parameterized-trigger:2.4;resolution:=optional,subversion:2.0.1-SNAPSHOT
Most probably the issue is in parameterized-trigger, but it's pretty strange that git plugin has dependency on subversion plugin. 
As concerning HPI/HPL dependency description I think that they should be the same, but I see  difference. If I build cvs plugin, HPI manifest doesn't contain dependencies, but test hpl has: Plugin-Dependencies: maven-plugin:2.0.1,subversion:1.11

Thank you.

**Comment by mcculls** [comment]
I know what you mean, so I've added a second commit that excludes transitive plugin dependencies since they'll be handled by the plugin manager. The results now match the original 1.54 plugin, but with improved detection of the Hudson version.

**Pull request merged**
